### ISSUE TITLE
[UIImage croppedImageWithFrame:angle:]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by hh2k** [XAM-Consulting/Xam.Plugins.ImageCropper#1]
I am getting a crash in my app when I am tapping done after cropping my image. See stack trace. It's working fine in the simulator but crashing on the device (Iphone 6 IOS 10 and iphone 4s IOS 9).

Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[UIImage croppedImageWithFrame:angle:]: unrecognized selector sent to instance 0x17a46040
Native stack trace:
    0   CoreFoundation                      0x24827933 <redacted> + 150
    1   libobjc.A.dylib                     0x23fc2e17 objc_exception_throw + 38
    2   CoreFoundation                      0x2482d2b5 <redacted> + 0
    3   CoreFoundation                      0x2482aee1 <redacted> + 700
    4   CoreFoundation                      0x24756238 _CF_forwarding_prep_0 + 24
    5   BWF.iOS                             0x00098fd5 -[TOCropViewController doneButtonTapped] + 2356
    6   BWF.iOS                             0x000959e3 __35-[TOCropViewController viewDidLoad]_block_invoke + 30
    7   BWF.iOS                             0x0009b235 -[TOCropToolbar buttonTapped:] + 616
    8   UIKit                               0x28dda755 <redacted> + 80
    9   UIKit                               0x28dda6e1 <redacted> + 64
    10  UIKit                               0x28dc26d3 <redacted> + 466
    11  UIKit                               0x28dda005 <redacted> + 604
    12  UIKit                               0x28dd9c7f <redacted> + 646
    13  UIKit                               0x28dd268f <redacted> + 642
    14  UIKit                               0x28da3125 <redacted> + 204
    15  UIKit                               0x28da16d3 <redacted> + 5010
    16  CoreFoundation                      0x247e9dff <redacted> + 14
    17  CoreFoundation                      0x247e99ed <redacted> + 452
    18  CoreFoundation                      0x247e7d5b <redacted> + 794
    19  CoreFoundation                      0x24737229 CFRunLoopRunSpecific + 520
    20  CoreFoundation                      0x24737015 CFRunLoopRunInMode + 108
    21  GraphicsServices                    0x25d27ac9 GSEventRunModal + 160
    22  UIKit                               0x28e0b189 UIApplicationMain + 144
    23  libXamarin.iOS.dll.dylib            0x0069aa08 wrapper_managed_to_native_UIKit_UIApplication_UIApplicationMain_int_string___intptr_intptr + 272
    24  libXamarin.iOS.dll.dylib            0x0060b6d0 UIKit_UIApplication_Main_string___intptr_intptr + 52
    25  libXamarin.iOS.dll.dylib            0x0060b690 UIKit_UIApplication_Main_string___string_string + 204
    26  libBWF.iOS.exe.dylib 0x0054ffdc BWF_iOS_Application_Main_string__ + 188
    27  libmscorlib.dll.dylib               0x00b179f0 wrapper_runtime_invoke_object_runtime_invoke_dynamic_intptr_intptr_intptr_intptr + 256
    28  libmonosgen-2.0.dylib               0x002a2bfd mono_jit_runtime_invoke + 1652
    29  libmonosgen-2.0.dylib               0x002fa0a1 do_runtime_invoke + 78
    30  libmonosgen-2.0.dylib               0x002fbc81 mono_runtime_exec_main + 608
    31  libmonosgen-2.0.dylib               0x002fb96f mono_runtime_run_main + 630
    32  libmonosgen-2.0.dylib               0x0028d21f mono_jit_exec + 162
    33  libxamarin-debug.dylib              0x005183fc xamarin_main + 2508
    34  BWF.iOS              0x000c265f main + 112
    35  libdyld.dylib                       0x243df873 <redacted> + 2

  at at (wrapper managed-to-native) UIKit.UIApplication:UIApplicationMain (int,string[],intptr,intptr)
  at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Users/builder/data/lanes/3426/6c3fee4d/source/xamarin-macios/src/UIKit/UIApplication.cs:79
  at UIKit.UIApplication.Main (System.String[] args, System.String principalClassName, System.String delegateClassName) [0x00038] in /Users/builder/data/lanes/3426/6c3fee4d/source/xamarin-macios/src/UIKit/UIApplication.cs:63
  at BWF.iOS.Application.Main (System.String[] args) [0x00008] in /Users/henrikhansen/Projects/BWF/BWF/iOS/Main.cs:17

**Comment by hh2k** [comment]
This is not an issue for me anymore

**Comment by ilker55** [comment]
So how did you solved it? I'm having the same issue.

**Comment by hh2k** [comment]
@ilker55 The error just disappeared again. Might be after upgrading to ios10, so try to upgrade and update all packages.

**Comment by ilker55** [comment]
I've already everything updated (iOS 10.x & packages), but I still get the same error.

**Comment by gutierrezralph** [comment]
Same error here.
