### ISSUE TITLE
contains incomplete bitcode

### ISSUE THREAD

**Issue by KalpeshChheda** [XAM-Consulting/Xam.Plugins.ImageCropper#10]
Hi @jessejiang0214,

While upload IPA I am getting below error.

ERROR ITMS-90668: "Invalid Bundle Executable. The executable file 'GoodsManV1.iOS.app/Frameworks/TOCropViewController.framework/TOCropViewController' contains incomplete bitcode. To compile binaries with complete bitcode, open Xcode and choose Archive in the Product menu."

**Comment by RaFaGG** [comment]
I have the same error. Any update?

**Comment by futurify-tanhoang** [comment]
I encountered the same problem. How to fix it?

**Comment by RaFaGG** [comment]
Hi, i talk with @jessejiang0214 and he say me:
Can you build NuGet package with this project, and upload to Apple Store?

What I changed is in Xam.Plugins.ImageCropper/iOS/extern/Makefile

IOS_GIT_BRANCH=master
XBUILD=/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild
WORKSPACE=TOCropViewControllerExample.xcodeproj
WORKSPACE_DIR=ios/TOCropViewController
SCHEME=TOCropViewController
BUILD_ROOT=build/Build/Products
VALID_ARCHS="armv7 armv7s arm64 i386 x86_64"

all: clean TOCropViewController.framework

Podfile.lock:
mkdir -p ios
cd ios && git clone https://github.com/TimOliver/TOCropViewController.git
cd ios/TOCropViewController && git checkout $(IOS_GIT_BRANCH)

TOCropViewController-iphonesimulator: Podfile.lock
cd $(WORKSPACE_DIR) && $(XBUILD) -project $(WORKSPACE) -scheme $(SCHEME) -sdk iphonesimulator -configuration Release VALID_ARCHS=$(VALID_ARCHS) ENABLE_BITCODE=NO ONLY_ACTIVE_ARCH=NO EFFECTIVE_PLATFORM_NAME="-iphonesimulator" -derivedDataPath build clean build

TOCropViewController-iphoneos: Podfile.lock
cd $(WORKSPACE_DIR) && $(XBUILD) -project $(WORKSPACE) -scheme $(SCHEME) -sdk iphoneos -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_BITCODE=NO -derivedDataPath build clean build

cp -R $(WORKSPACE_DIR)/$(BUILD_ROOT)/Release-iphoneos/TOCropViewController.framework TOCropViewController.framework

TOCropViewController.framework: TOCropViewController-iphoneos TOCropViewController-iphonesimulator
lipo -create -output $@/TOCropViewController $^

clean:
rm -rf ios

.PHONY: all clean

I added ENABLE_BITCODE=NO for OS and simulator.
Thanks

I try it but i have another problem (I do not know if it's related to the plugin). @KalpeshChheda @futurify-tanhoang can you try the fix?

**Comment by RaFaGG** [comment]
The fix is correct. Thanks @jessejiang0214. I submit a pull request with the changes in #11 .
