### ISSUE TITLE
Error while running sample code for IOS - Error - Framework not found

### ISSUE THREAD

**Issue by ravikanasagra1** [XAM-Consulting/Xam.Plugins.ImageCropper#13]
When I tried to run the code for IOS simulator, I received below error.

MTOUCH : warning MT1302: Could not extract the native framework 'TOCropViewController.framework' from '/Users/admin/Desktop/Xam.Plugins.ImageCropper-master/Sample/iOS/obj/iPhoneSimulator/Debug/mtouch-cache/TOCropViewController.framework.zip'. Please ensure the native framework was properly embedded in the managed assembly (if the assembly was built using a binding project, the native framework must be included in the project, and its Build Action must be 'ObjcBindingNativeFramework').
clang : error : linker command failed with exit code 1 (use -v to see invocation)
error MT5209 : Native linking error : framework not found TOCropViewController
MTOUCH : error MT5202: Native linking failed. Please review the build log.
    1 Warning(s)
    3 Error(s)

**Comment by Axemasta** [comment]
Why did you close this? I have this as an issue, did you get it working? if so please share how you fixed it.

**Comment by ravikanasagra1** [comment]
There is one make file available. when run it on your mac, it would download actual native project and create a framework file required. 

I expect a framework file instead of make file as solution. 

Let me open this issue as per request.

**Comment by Axemasta** [comment]
Right ok, I didn't quite realise that. I opened up the folder with the make file, entered "make" into my terminal, everything installed and now iOS will build & run. Thanks!
