### ISSUE TITLE
SIGABRT while executing native code.

### ISSUE THREAD

**Issue by rapcgutz** [XAM-Consulting/Xam.Plugins.ImageCropper#4]
I got this message when i launch the apps then Choose "Take Photo" or "Photo Library"

Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
Failed to Stop app:  An error occured on client IDB430795 while executing a reply for topic xvs/idb/4.3.0.795/stop-app
The app has been terminated.
The app has been terminated.

**Comment by jessejiang0214** [comment]
Hi @gutierrezralph 

Can you try add "-ObjC" in to iOS project->Options->iOS Build-> Addition mtouch arguments .

If it still cannot work, would you please give us a demo project to reproduce this?

Thanks

**Comment by rapcgutz** [comment]
Hello,

I already fixed the "SIGABRT" error after updating Xamarin.Forms and Plugin.Media
but right now i have issue on 
"using Xam.Plugins.ImageCropper.iOS" was not recognized, 
so that "TOCropViewController","TOCropViewControllerDelegate"
and "void DidCropToImage(TOCropViewController cropViewController, UIImage image, CoreGraphics.CGRect cropRect, nint angle)" was not recognized too. Please see link below for the unrecognize interface and override function. 

Note: the copy i used is your upload project .

http://imageshack.com/a/img923/6590/10D7yq.png
http://imageshack.com/a/img924/5889/Quzh2k.png
