### ISSUE TITLE
Circular crop - Feature

### ISSUE THREAD

**Issue by rapcgutz** [XAM-Consulting/Xam.Plugins.ImageCropper#6]
Circular crop view was available ? 
If yes, Do you have any sample? 

![image](https://cloud.githubusercontent.com/assets/26339824/24872586/8162d3aa-1e50-11e7-9bc4-2cc12f37af75.png)

same issue here on TimOliver but i don't know how to use the features in C#. 
[https://github.com/TimOliver/TOCropViewController/issues/75](url)

**Comment by jessejiang0214** [comment]
@gutierrezralph  check new version 1.1.0
