### ISSUE TITLE
Done event - Question

### ISSUE THREAD

**Issue by rapcgutz** [XAM-Consulting/Xam.Plugins.ImageCropper#7]
**Question**

I have button on subview of Cropper and i want to call override void DidCropToImage() when i press the button in subview of cropper screen.  I need to crop the image once i clicked the button (like "done").
Any hints or sample?

**Comment by jessejiang0214** [comment]
In Android, the button create by ourselves, In iOS you can override DidCropToImage function.
https://github.com/XAM-Consulting/Xam.Plugins.ImageCropper/blob/master/Sample/iOS/Renderer/CropViewRenderer.cs#L88
